substitutions:

  # Secrets and Passwords - Update values in secrets.yaml
  wifi_ssid1: !secret wifi_ssid_gvf
  wifi_password1: !secret wifi_password_gvf
  wifi_ssid2: !secret wifi_ssid_brasil
  wifi_password2: !secret wifi_password_brasil
  fallback_password: !secret fallback_password

  # ENTITIES

  weather_entity:           "weather.forecast_home"

  # Define logging level: NONE, ERROR, WARN, INFO, DEBUG (Default), VERBOSE, VERY_VERBOSE
  log_level: "WARN"

  # SETTINGS
  secondary_language:        "es"
  timezone:                  "Europe/Madrid"

  # ICONS
#  previous_track_icon:        "\U000F04AE"
#  next_track_icon:            "\U000F04AD"
#  volume_off_icon:            "\U000F0581"
#  volume_on_icon:             "\U000F057E"
#  volume_minus_icon:          "\U000F075E"
#  volume_plus_icon:           "\U000F075D"
#  repeat_all_icon:            "\U000F0456"
#  repeat_off_icon:            "\U000F0457"
#  repeat_one_icon:            "\U000F0458"
#  media_source:               "\U000F0206"
